name: Free RDP (Ngrok v3)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Create RDP user and enable RDP
      run: |
        net user rdpuser P@ssw0rd123 /add
        net localgroup administrators rdpuser /add
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download ngrok (v3)
      run: |
        Invoke-WebRequest -Uri https://ngrok.com/downloads/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath $env:USERPROFILE\ngrok

    - name: Configure ngrok authtoken
      run: |
        $ngrokPath = "$env:USERPROFILE\ngrok\ngrok.exe"
        & $ngrokPath config add-authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

    - name: Start ngrok TCP tunnel
      run: |
        $ngrokPath = "$env:USERPROFILE\ngrok\ngrok.exe"
        Start-Process -FilePath $ngrokPath -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -Seconds 20
        $retry = 0
        while ($retry -lt 5) {
          try {
            Invoke-WebRequest -Uri http://127.0.0.1:4040/api/tunnels -OutFile tunnel.json
            break
          } catch {
            Start-Sleep -Seconds 5
            $retry++
          }
        }

    - name: Show RDP Info
      run: |
        echo "======================================="
        echo "✅ RDP Details:"
        echo "👤 Username: rdpuser"
        echo "🔑 Password: P@ssw0rd123"
        echo "🌐 Tunnel Info (check for public_url):"
        Get-Content tunnel.json
        echo "======================================="
